### ISSUE TITLE
readme inssue

### ISSUE THREAD

**Issue by ahkui** [corex/lmodel#1]
$this->app->register('CoRex\Laravel\Model\ModelProvider');
change to
$this->app->register('CoRex\Laravel\Model\ModelServiceProvider');

**Comment by corex** [comment]
Hi joonkui95.

Sorry for not getting back until now. I have had some problems with my hosting company so I have not seen this issue until now. I am so sorry.

About the issue - it is fixed + some other issues.  Version 1.1.0 has arrived.

Thanks for getting back to me on this matter.
