### ISSUE TITLE
ENUM

### ISSUE THREAD

**Issue by GeometryRamiroGarcia** [corex/lmodel#2]
Hello @corex , one of my tables has a field with data type enum and does not generate the model.

`Doctrine\DBAL\DBALException  : Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.`

Thanks for any help you can give me.

**Comment by corex** [comment]
Hi there.

The error is not related to corex/lmodel. It is a problem in third-party package called doctrine/dbal which I am using to get get information from the database.

However, I have analyzed it a little and I think I have a workaround where you still can have your model generated. The "enum" is interpreted as "string" but you should be able to use it.

I need to test some more and write some tests for it, before I release. I will write here when done.

**Comment by corex** [comment]
corex/lmodel 1.1.2 released.
